language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  # Disable for now as pylint is failing
  #- "nightly" # currently points to 3.6-dev
install: 
  - pip3 install -r requirements.txt -r dev_requirements.txt
script: make check

