language: python
python:
  - "3.4"
  - "3.5"
  # Disable for now as pylint is failing
  #- "3.6"
  #- "nightly" # currently points to 3.6-dev
install: 
  - pip3 install -r requirements.txt -r dev_requirements.txt
  - pip3 install -U coala-bears
script: make check

